version: 0.1
phases:
  install:
    commands:
      - wget https://s3-ap-northeast-1.amazonaws.com/dynamodb-local-tokyo/dynamodb_local_latest.tar.gz
      - mkdir dynamodb
      - tar zxf dynamodb_local_latest.tar.gz -C ./dynamodb
      - cd dynamodb/ ; java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &
      - cd dev/ ; bundle install
      - cd dev/sam-client ; bundle install
      - cd dev/sam-client ; bundle exec rake db:migrate SINATRA_ENV=test
  pre_build:
    commands:
      - cd dev/sam-app ; ruby tests/unit/*.rb
      - cd dev/sam-app ; ruby tests/unit/**/test_*.rb
      - cd dev/sam-app ; ruby tests/unit/**/*_test.rb
      - cd dev/sam-client ; bundle exec rspec
      - cd dev/sam-client ; ruby api/tests/**/test_*.rb
  build:
    commands:
      - bundle install --deployment --without test development
      - cp -r ./vendor dev/sam-app/hello_world
      - cp -r ./vendor dev/sam-app/fizz_buzz
      - cp -r ./vendor dev/sam-client
      - cp -r ./vendor dev/sam-client/api/hello_world
      - rm -rf ./vendor
      - cd dev/sam-client ; npm install
      - cd dev/sam-client ; npm rebuild node-sass
      - cd dev/sam-client ; npm run build
  post_build:
    commands:
      # env var BUILD_ARTIFACT_BUCKET is defined in ci.yaml
      - aws cloudformation package
        --template-file dev/template.yaml
        --s3-bucket $BUILD_ARTIFACT_BUCKET
        --output-template-file SamDeploymentTemplate.yaml
artifacts:
  type: zip
  files:
    - SamDeploymentTemplate.yaml