source 'http://rubygems.org'

gem 'sinatra'
gem "sinatra-contrib",require: false
gem 'activerecord', '~> 4.2', '>= 4.2.6', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem "tux"
gem 'json'
gem 'rack'
gem 'rack-contrib'
gem "httparty"
gem "rake"
gem 'aws-record'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
  gem 'test-unit'
  gem 'mocha'
  gem "simplecov"
  gem 'rubocop', require: false
end
